services:
  cloud_alloc:
    build:
      context: .
    env_file:
      - path: ./env/docker.env
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: on-failure
    env_file:
      - path: ./env/docker.env
    user: postgres
    volumes:
      - cloud_alloc-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    restart: on-failure
    ports:
      - 9092:9092
    volumes:
      - kafka-data:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  minio:
    image: minio/minio
    restart: on-failure
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    env_file:
      - path: ./env/docker.env
    command: server --console-address ":9001" /data

volumes:
  cloud_alloc-data:
  kafka-data:
  minio-data: