spring:
  application:
    name: cloud_alloc
    service:
      account:
        min-size-default: 1024

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - https://www.googleapis.com/auth/drive   # drive access
              - https://www.googleapis.com/auth/userinfo.email

logging:
  level:
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG